### ISSUE TITLE
关于版本问题

### ISSUE THREAD

**Issue by cxx-cindy** [Chiang97912/QA_LSTM_ATTENTION#3]
请问您的tensorflow和python的版本是多少？

**Comment by Chiang97912** [comment]
Python 3.6, Tensorflow 1.14

**Comment by cxx-cindy** [comment]
谢谢您，但是我遇到以下这个错误，能帮我看下是什么原因吗？
2021-09-16 13:50:08.851285: E tensorflow/stream_executor/cuda/cuda_dnn.cc:81] CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(3666): 'cudnnPoolingForward( cudnn.handle(), pooling_desc.handle(), &alpha, src_desc.handle(), input_data.opaque(), &beta, dest_desc.handle(), output_data->opaque())'
Traceback (most recent call last):
  File "D:\Anaconda\envs\tensorflow 1\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "D:\Anaconda\envs\tensorflow 1\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Anaconda\envs\tensorflow 1\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: cudnn PoolForward launch failed
	 [[{{node attention_encoder/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 300, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/attention_encoder/MaxPool_grad/MaxPoolGrad-0-TransposeNHWCToNCHW-LayoutOptimizer)]]
	 [[{{node acc/acc/_47}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_258289_acc/acc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
